before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  
language: ruby
rvm:
 - 2.3.3

addons:
  apt:
    - google-chrome-stable
    - chromium-chromedriver
   
RSpec.configure do |config|
   config.before(:each, type: :system) do
-    driven_by :selenium, using: :chrome
+    driven_by :selenium, using: :chrome, options: { args: ["headless", "disable-gpu", "no-sandbox", "disable-dev-shm-usage"] }
   end
 end